version: '3.7'

services:
  postgres:
    container_name: nest_db_postgre
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - api_db_data:/var/lib/postgresql/data
volumes:
  api_db_data:
